### ISSUE TITLE
图片无法处理

### ISSUE THREAD

**Issue by yangxunj** [lxfater/inpaint-web#45]
CPU:AMD5500 
显卡:AMD6650XT 
系统:Win11
浏览器:Chrome
下载了30MB+70MB两个文件，然后上传了本地的“pic.jpg”，进度从0走到100%以后，没有进行处理，跟demo表现不一致。demo会在屏幕上方有一个timeline，方便回滚处理，但是，我这边网页上timeline是空的，屏幕上的图片看起来也没有任何处理

**Comment by lxfater** [comment]
刷新一下试试，你可以截图

**Comment by xk756** [comment]
![WeChatc28e230baeabdd449b8cf1735775e9a2](https://github.com/lxfater/inpaint-web/assets/46642091/ac1d0835-f460-41ba-a12c-a22f2e11f91b)
没有用，

**Comment by QGMoe** [comment]
好像是因为在图片过大的情况下（大约16,00万像素左右），超分辨率完成后在渲染过程中数组的长度炸了，我看控制台报了如下错误：

```
superResolution RangeError: Invalid array length
    at Array.push (<anonymous>)
    at ZS (index-wKMmwxyL.js:76:37509)
    at pS (index-wKMmwxyL.js:76:38142)
    at async index-wKMmwxyL.js:76:46849
```
